server:
  port: 8088

spring:
  application:
    name: nk-order-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/nk-order-db
    username: nk-order-user
    password: nk-order-pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        orderCalculatedProducer-out-0:
          destination: nk.order.ms.event.order-calculated
          producer:
            required-groups: nk-order-ms-group
      rabbit:
        bindings:
          orderCalculatedProducer-out-0:
            producer:
              exchange-type: topic # ou direct, dependendo da necessidade
              auto-bind-dlq: true  # Cria Dead Letter Queue automaticamente
              bindings: # Define a fila e os parâmetros
                queue-name: nk-order-queue
              queue-properties: # Define a persistência e exclusão
                durable: true
                exclusive: false
                auto-delete: false