server:
  port: 8088

spring:
  application:
    name: nk-order-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/nk-order-db
    username: nk-order-user
    password: nk-order-pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true